name: 'Test'

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.0.0
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Eslint check
        run: npm run eslint

      - name: Prettier check
        run: npm run prettier

      - name: Testing code
        run: npm run test
